// This source file was auto-generated by ClassMate++
// Created: 14 Aug 2021 3:45:48 pm
// Copyright (c) 2021, HurleyWorks

// ctor
CameraSensor::CameraSensor ()
{	
}

// dtor
CameraSensor::~CameraSensor ()
{	
}

